### ISSUE TITLE
404 Error on ApiAuthApi

### ISSUE THREAD

**Issue by ringcsbi** [bufferapp/lookerpy#4] opened 2017-12-15 00:29 UTC
Hello,

I seem to be getting an exception when calling the ApiAuthApi -> login: (404). This is what I am receiving back when I run the script that tests authorization. We are using python 3.6 to run this script. Is there any way to change the host for the HTTP Request? Any help about this issue would be greatly appreciated. Thank you. 

![screen shot 2017-12-14 at 5 25 09 pm](https://user-images.githubusercontent.com/33106858/34020876-e715ff68-e0f3-11e7-9e91-2354db8a2e21.png)

**Comment by davidgasquez** [comment] 2017-12-15 11:11
Hey there @ringcsbi! I'm not really sure what could be the cause of this issue. If it's helpful, the `lookerpy` code was generated using Swagger and might be outdated! 

Would you mind sharing what were you trying to achieve? 

There's another [Python library focused only on running looks and queries](https://github.com/bufferapp/pylooker) in case that's what you were trying.

**Comment by ringcsbi** [comment] 2017-12-18 18:04
Oh gotcha! We were trying to pull looks and put them into gmail. It looks like the other Python Library might be what we need. Thanks!

**Comment by davidgasquez** [comment] 2017-12-19 08:36
Awesome! Let me know if you hit any snags with [`pylooker`](https://github.com/bufferapp/pylooker). Closing this issue for now! 😉

**Closed as completed by davidgasquez** 2017-12-19 08:36 UTC
